<#
.SYNOPSIS
    Interactive builder that generates a custom print job cleanup script.

.DESCRIPTION
    Prompts the user for one or more print servers (by hostname or IP),
    then generates a standalone PowerShell script that automatically
    clears errored print jobs from those servers.
    The user is prompted to save the generated script.

.NOTES
    Author: Andy (TuxCode)
    Version: 3.1
    License: MIT
#>

Add-Type -AssemblyName System.Windows.Forms

# --- Function to get print servers interactively ---
function Get-PrintServers {
    Write-Host "`n🖨️  Let's configure your print servers." -ForegroundColor Cyan
    $servers = @()

    do {
        $server = Read-Host "Enter a Print Server hostname or IP (or press Enter to finish)"
        if ($server) { $servers += $server }
    } while ($server)

    if ($servers.Count -eq 0) {
        Write-Warning "No print servers entered. Exiting."
        exit
    }

    Write-Host "`n✅ Print servers configured:" -ForegroundColor Green
    $servers | ForEach-Object { Write-Host " - $_" }

    return $servers
}

# --- Function to build and save the custom script ---
function Build-CustomScript {
    param ([string[]]$Servers)

    # ✅ Fix: wrap ForEach-Object + join in parentheses
    $serverList = ($Servers | ForEach-Object { "'$_'" }) -join ", "

    # ✅ Fix: escape `$` symbols in here-string with backticks
    $scriptTemplate = @"
<#
.SYNOPSIS
    Automatically clears errored print jobs from configured servers.

.DESCRIPTION
    Generated by Clear-ErrorPrintJobs-Builder.ps1
    Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#>

Import-Module PrintManagement -ErrorAction Stop

# Your configured print servers:
`$PrintServers = @($serverList)

foreach (`$server in `$PrintServers) {
    Write-Host "`n--- Checking print server: `$server ---" -ForegroundColor Cyan

    try {
        `$printers = Get-Printer -ComputerName `$server -ErrorAction Stop
    }
    catch {
        Write-Warning "⚠️  Unable to connect to `$server. Skipping..."
        continue
    }

    foreach (`$printer in `$printers) {
        `$printJobs = Get-PrintJob -ComputerName `$server -PrinterName `$printer.Name |
            Where-Object { `$_.JobStatus -like "*Error*" }

        foreach (`$job in `$printJobs) {
            try {
                Remove-PrintJob -ComputerName `$server -PrinterName `$printer.Name -ID `$job.ID
                Write-Host "🗑️  Cleared job ID `$(`$job.ID) on printer `$(`$printer.Name)" -ForegroundColor Green
            }
            catch {
                Write-Warning "⚠️  Could not cancel job ID `$(`$job.ID) on printer `$(`$printer.Name): `$_"
            }
        }
    }
}
"@

    # --- Prompt user to save the generated script ---
    $saveDialog = New-Object System.Windows.Forms.SaveFileDialog
    $saveDialog.Filter = "PowerShell Script (*.ps1)|*.ps1"
    $saveDialog.Title = "Save Your Custom Print Cleanup Script"
    $saveDialog.FileName = "Clear-ErrorPrintJobs-Custom.ps1"

    if ($saveDialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
        $scriptTemplate | Out-File $saveDialog.FileName -Encoding UTF8
        Write-Host "`n💾 Saved custom script to:`n$($saveDialog.FileName)" -ForegroundColor Yellow
        Write-Host "`n✅ You can now schedule this script in Task Scheduler to run automatically."
    }
    else {
        Write-Warning "Save canceled. No file was created."
    }
}

# --- MAIN EXECUTION ---
$servers = Get-PrintServers
Build-CustomScript -Servers $servers
